name: eclipse_works_todo_list
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  meta: ^1.9.1
  clock: ^1.1.1
  slugid: ^1.1.2
  flutter_easyloading: ^3.0.5
  validatorless: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1
  mocktail: ^0.3.0
  faker_dart: ^0.1.11

flutter:
  uses-material-design: true
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/source-sans-pro-v21-latin-regular.ttf
          style: normal
          weight: 400
